# Default values for chaosblade.

# chaosblade-operator
operator:
  repository: chaosbladeio/chaosblade-operator
  version: 0.10.0
  # image.pullPolicy: must be Always|IfNotPresent|Never
  pullPolicy: IfNotPresent
  # qps of kubernetes client
  qps: 20
  reconcileCount: 20

blade:
  repository: chaosbladeio/chaosblade-tool
  version: 0.10.0
  pullPolicy: IfNotPresent

env:
  logLevel: info

webhook:
  enable: true

daemonset:
  enable: true

remove:
  blade:
    interval: 72h